### PR TITLE
Moving token to enviroment file for security

### PR DESCRIPTION
**Pull request by gapidobri**

### CODE REVIEW

**Comment by MaticBabnik** [comment]
Please end use semicolons. Otherwise seems gucci.

**Comment by marwuint** [comment]
> Please end use semicolons
what is that suppose to mean

**Comment by MaticBabnik** [comment]
> > Please end use semicolons
> 
> @MaticBabnik what is that suppose to mean
> 
> 

focking gboard.

**Comment by marwuint** [comment]
>  Please use semicolons

Ummm, NO!?

**Pull request merged**
